language: generic
os: osx
osx_image: xcode9.4
script:
    - "export PS4='+(${BASH_SOURCE}:${LINENO}): ${FUNCNAME[0]:+${FUNCNAME[0]}(): }'"
    - (cd $(brew --repository); git describe --all)
    - /bin/bash -x /usr/local/Homebrew/Library/Homebrew/brew.sh install --debug qt5