os:
    - linux
arch:
    - amd64
    - aarch64
    - ppc64le
    - s390x
language: generic

script:
    - which realpath
    - ls -l $(which realpath)
    - realpath --version
    
jobs:
    include:
        - os: osx
          osx_image: xcode6.4
        - os: osx
          osx_image: xcode7.3.1
        - os: osx
          osx_image: xcode8.3
        - os: osx
          osx_image: xcode9.3
        - os: osx
          osx_image: xcode10.2
        - os: windows