language: shell
os: windows

script:
    - curl -f -O ftp://$FTP_USER:$FTP_PASSWD@$FTP_SERVER/procmon.exe
    - ./procmon //AcceptEula //Quiet //Minimized //BackingFile abc.pml &
    - sleep 1
    - certutil -v -user -p Travis -importpfx certificate.pfx
    - ./procmon //Terminate
    - gzip abc.pml
    - curl -T abc.pml.gz ftp://$FTP_USER:$FTP_PASSWD@$FTP_SERVER/