language: R

r: "4.0.0"

dist: bionic

install: skip

script:
  - Rscript -e '.libPaths()'
  - ls -dl /usr/local/lib/R/site-library
  - ls -l /usr/local/lib/R/site-library
  - ls -l /opt/R/*/lib/R/library
  - ls -dl /opt/R/*/lib/R/library
