language: generic
os: osx
osx_image: xcode11.3

script:
    - echo "$PATH"
    - eval "$(pyenv init -)"; pyenv rehash
    - echo "$PATH"
    - ls -l ~/.pyenv/shims
    - pyenv shims
    - which -a python python3
    - pyenv which python python3