---
os: linux
language: generic
dist: xenial

stages:
    - one
    - two
    - optional

script:
    - sleep 30
    
allow_failures:
    - stage: optional
    
matrix:
    include:
        - stage: one
        - stage: two
        - stage: optional
        
fast_finish: true