language: java
dist: xenial
jdk:
  - openjdk13
script:
  - echo "$PATH"
  - which -a java
  - java -version
  - |
    python -c 'if True:
        import os
        print os.environ["PATH"]
        os.system("which -a java")
        os.system("java -version")
        '