language: generic
os: osx
osx_image: xcode9.4
script:
    - "export PS4='+(${BASH_SOURCE}:${LINENO}): ${FUNCNAME[0]:+${FUNCNAME[0]}(): }'"
    - (cd $(brew --repository); git describe --all)
    - sed -Ei.old 's|(/usr/bin/env -i "\$\{FILTERED_ENV\[@\]\}" /bin/bash)|\1 -x|' /usr/local/bin/brew && diff /usr/local/bin/brew{.old,}
    - bash -x /usr/local/bin/brew install --debug qt5