---
os:
  - linux
matrix:
    include:
        - dist: xenial
        - dist: trusty

language: shell
script:
    - dpkg --list ca-certificates | cat
    - openssl s_client -servername scan.coverity.com -connect scan.coverity.com:443 2>/dev/null </dev/null
    - openssl crl2pkcs7 -nocrl -certfile /etc/ssl/certs/ca-certificates.crt | openssl pkcs7 -print_certs -text -noout | grep -P '^\s+Subject:.*Entrust'
    - curl -v https://scan.coverity.com/scripts/travisci_build_coverity_scan.sh -o travisci_build_coverity_scan.sh.orig