os: osx
osx_image: xcode8.3

script:
    - ls -l /usr/local/{opt/openssl*,Cellar/openssl*{,/*/lib}}
    - brew update
    - ls -l /usr/local/{opt/openssl*,Cellar/openssl*{,/*/lib}}
    - brew upgrade pyenv
    - ls -l /usr/local/{opt/openssl*,Cellar/openssl*{,/*/lib}}