language: shell
os: windows

script:
    - powershell -Command "ls Cert:\LocalMachine"
    - certutil -v -user -p Travis -importpfx certificate.pfx
    - certutil -v -p Travis -importpfx certificate.pfx