os: windows
#version: ~> 1.0

jobs:
    include:
    - language: c
    - language: cpp
    - language: node_js
    - language: rust
    - language: go
    - language: csharp
    - language: generic
    - language: julia
    - language: minimal
    - language: powershell
    - language: script
    - language: sh
