---
os: linux
language: generic

matrix:
    include:
        - dist: precise
          name: precise
        - dist: trusty
          name: trusty
        - dist: xenial
          name: xenial
        - dist: bionic
          name: bionic

services:
    - docker
          
script:
    - docker --version