os: windows
language: shell

script: |
    which python; python --version
    python -c 'if True:
        import subprocess
        subprocess.check_call("echo bla-bla-bla", shell=True)
        subprocess.check_call("echo bla-bla-bla2 >&2", shell=True)
    '