---
language: python
os: linux
dist: bionic

  
script:
   - pyenv versions
   - ls -l /opt/python
   - echo "$PYENV_ROOT"; ls -l "$PYENV_ROOT"
   - pyenv install 2.7.14 --verbose
   - ls -l /opt/python
   - pyenv commands