---
sudo: required
language: python
python:
    - "3.5"
install:
    - ip a
    - sudo sysctl -w net.ipv6.conf.all.disable_ipv6=0
    - ip a
    - sudo sysctl -w net.ipv6.conf.lo.disable_ipv6=0
    - ip a
script:
    - python3 test.py
