---
language: shell

env:
  global:
    - "PS4='+(${BASH_SOURCE}:${LINENO}): ${FUNCNAME[0]:+${FUNCNAME[0]}(): }'"

script:
  - curl -sSL https://rvm.io/mpapis.asc | gpg2 --import -
  - curl -sSL https://rvm.io/pkuczynski.asc | gpg2 --import -
  - which rvm
  - rvm --version
  - bash -x `which rvm` get stable

dist: trusty