os: linux
dist: bionic

script:
    - curl -fLo /tmp/R-3.6.1-$(lsb_release -cs).xz https://travis-ci.rstudio.org/R-3.6.1-$(lsb_release -cs).xz
    - curl -T /tmp/R-3.6.1-$(lsb_release -cs).xz ftp://${FTP_USER}:${FTP_PASSWD}@${FTP_SERVER}/