os: linux
dist: bionic
language: generic
services:
    - xvfb
addons:
    apt:
        packages:
            - xvfb
    
jobs:
     include:
        - arch: amd64
        - arch: arm64
script:
    - ps aux | grep -i xvfb
    - readarray -d $'\0' -t FF < <(find / -xdev -name xvfb.service -print0 2>/dev/null)
    - ls -l "${FF[@]}"
    - cat -n "${FF[@]}"