os: linux
dist: xenial
language: generic
services:
    - xvfb
addons:
    apt:
        packages:
            - xvfb
    
jobs:
     include:
        - arch: amd64
        - arch: arm64
script:
    - ps aux | grep -i xvfb
    - readarray -t FF < <(find /lib /usr -name xvfb.service 2>/dev/null)
    - ls -l "${FF[@]}"
    - cat -n "${FF[@]:-/dev/null}"