os: windows
language: shell

install:
    - choco upgrade docker

script:
    - docker pull mcr.microsoft.com/cosmosdb/windows/azure-cosmos-emulator
    - docker run --name azure-cosmosdb-emulator --memory 2GB --isolation=hyperv -p 8081:8081 -p 8900:8900 -p 8901:8901 -p 8902:8902 -p 10250:10250 -p 10251:10251 -p 10252:10252 -p 10253:10253 -p 10254:10254 -p 10255:10255 -p 10256:10256 -p 10350:10350 mcr.microsoft.com/cosmosdb/windows/azure-cosmos-emulator &
    - sleep 60
    - docker ps -a -q
    - docker stop $(docker ps -a -q)
    