os: linux
dist: xenial
language: generic
script: |
  set -x
  MARIADB_MIRROR='nyc2.mirrors.digitalocean.com'
  MARIADB_GPG_KEY_NEW='0xf1656f24c74cd1d8'
  mariadb_version=10.1
  sudo apt-key adv --recv-keys --keyserver hkp://keyserver.ubuntu.com:80 ${MARIADB_GPG_KEY_NEW}
  sudo add-apt-repository "deb http://${MARIADB_MIRROR}/mariadb/repo/${mariadb_version}/ubuntu $TRAVIS_DIST main"
  travis_apt_get_update
  PACKAGES="mariadb-server-${mariadb_version}"
  sudo apt-get install -y  -o Dpkg::Options::='--force-confnew' $PACKAGES
  apt list --installed
  apt-mark showhold
  set +x