language: shell
os: windows

script:
    - powershell -Command "ls Cert:\LocalMachine"
    - certutil -v -user -p Travis -importpfx certificate.pfx
    - certutil -v -p Travis -importpfx certificate.pfx
    - certutil -user -store "My"
    - certutil -store "My"
    - powershell -Command "ls Registry::HKEY_CURRENT_USER\Software\Microsoft\SystemCertificates"
    - powershell -Command 'get-acl Registry::HKEY_CURRENT_USER\Software\Microsoft\SystemCertificates\My | fl *'