---
language: shell
      
script:
  - sudo apt-get install -yq --no-install-suggests --no-install-recommends postgresql-common
  - sudo service postgresql stop
  - sudo apt install -yq --no-install-suggests --no-install-recommends postgresql-11 postgresql-client-11
  - sudo service postgresql start 11
  - sudo -u postgres psql -c 'create database travis_ci_test;'

matrix:
  include:
    - dist: trusty
    - dist: xenial
    - dist: bionic