---
dist: xenial
language: shell
      
script:
    - for py in python python3 pip pip3; do which $py; $py --version; done
    - |
      git clone https://github.com/pyenv/pyenv.git ~/.pyenv;
      export PYENV_ROOT="$HOME/.pyenv";
      export PATH="$PYENV_ROOT/bin:$PATH"
    - pyenv global system 3.7.1
    - for py in python python3 pip pip3; do which $py; $py --version; done
