language: shell
version: ~> 1.0
os:
- linux
dist: xenial

env:
    global:
        - FILE=$HOME/foo

before_install:
- if [[ -d $FILE ]]; then rm -rf $FILE; fi

script: |
    if [[ -e "$FILE" ]]; then
        cat "$FILE"
    else
        echo "bla-bla-bla" >"$FILE"
    fi

cache:
    directories:
        - $FILE