---
language: shell
os:
  - linux


matrix:
    include:
        - dist: trusty
        - dist: xenial
        - dist: bionic
  
script:
   - python2 --version; python3 --version
   - ls -l /opt/python
   - |
    ubuntu_release=$(lsb_release -r -s)
    function check_release() {
        local python_version="$1"
        echo $python_version
        # travis-build/lib/travis/build/script/python.rb:install_python_archive
        for hosting in \
                storage.googleapis.com/travis-ci-language-archives/python \
                s3.amazonaws.com/travis-python-archives \
                language-archives.travis-ci.com/python ; do
            local url="https://${hosting}/binaries/ubuntu/${ubuntu_release}/x86_64/${python_version}.tar.bz2"
            echo "$url"
            curl --head "$url" | grep -Ee '^HTTP/'
        done
    }

    for python in 2.{6,7} 3.{3..8}; do
        for micro in "" .{0..16}; do
            check_release python-${python}${micro}
        done
    done
    # list of releases from https://bitbucket.org/pypy/pypy/downloads/
    for pypy in pypy2 pypy3 pypy{2,3}-{5.{7{,.0,.1},8{,.0,.1},9{,.0},10{,.0},11{,.0}},6.0{,.0}}; do
        check_release ${pypy}
    done
    for pypy in pypy{2.7,3.{5,6}} pypy{27,3{5,6}}-7.{0{,.0,.1},1{,.0,.1}}; do
        check_release ${pypy}
    done
