language: generic
os: osx
osx_image: xcode9.4
script:
    - "export PS4='+(${BASH_SOURCE}:${LINENO}): ${FUNCNAME[0]:+${FUNCNAME[0]}(): }'"
    - (cd $(brew --repository); git describe --all)
    - BREW=$(readlink $(which brew))
    - sed -Ei.old 's|(/usr/bin/env -i "\$\{FILTERED_ENV\[@\]\}" /bin/bash)|\1 -x|' $BREW && diff ${BREW}{.old,}
    - bash -x $BREW install --debug qt5