os: linux
dist: bionic

script:
  - |
    for p in python pip python2 python3 pip3; do
      which $p
      pyenv which $p
      $p --version
    done
  - pyenv versions
  
jobs:
  include:
    - language: generic
    - language: minimal
    - language: python