language: shell
version: ~> 1.0
os:
- linux
- osx
- windows
script:
- source my_travis_terminate.sh
- set
- echo $$; echo $BASHPID
- ( echo $$; echo $BASHPID; exit 1 )
- bash -c 'declare -F travis_terminate exit'