language: java
dist: xenial
jdk:
  - openjdk13
script:
  - echo "$PATH"
  - which -a java
  - java -version
  - which python
  - python -c 'import os; print os.environ["PATH"]; os.system("which -a java")'
  - /usr/bin/python -c 'import os; print os.environ["PATH"]'
  - pyenv --version
