---
language: shell
      
addons:
  postgresql: 11
  apt:
    packages:
      - postgresql-11
      - postgresql-client-11
services:
  - postgresql
  
script:
  - psql -c 'create database travis_ci_test;' -U postgres -w

matrix:
  include:
    - dist: trusty
    - dist: xenial
    - dist: bionic