language: android
dist: xenial

android:
  components:
    - tools
    - platform-tools
    - extra-android-m2repository

    # The BuildTools version used by your project
    - build-tools-28.0.3

    # The SDK version used to compile your project
    - android-28

licenses:
    - 'android-sdk-license-.+'

before_install:
  #- yes | sdkmanager "platforms;android-28"
  #- yes | sdkmanager "emulator" "tools" "platform-tools"
  #- yes | sdkmanager --licenses
  #- yes | sdkmanager "build-tools;28.0.3"
  
script:
    - which android-update-sdk