---
language: minimal
os: linux

matrix:
    include:
        - dist: trusty
        - dist: xenial
        - dist: bionic

  
script:
    - |
        for cmd in python python2 python3 pip pip2 pip3; do
            which $cmd || true
            $cmd --version || true
        done
   