os: linux
language: shell
script:
- set
env:
  global:
    secure: Dc8yfBCUHzldZn3Z2yKnIHJnPOsKoDzE7PnS282iKRiHX2Xuj8uDqkXT/gHpop8uwni0NDZthonBHG5tcLKT2szTkMjWEfmppFbsXZ4iW3FAdjBtGOb76+x3fs2sR9MX1cIIwkqPG2NtZExdPtoEvRBMxkNWib68tjJ//4mTIWVIUaUYpcaQ5ORoRaV1N5Jp3j8CH+OjtJM9InAcSWCZ6Xx3p55taawfGxV6o0Flp3Lk/pcsOWNgd2nITKWEPZoMQH5+uC+OPitI8cj6fSLUtugYdRHSZhlru1hkOgDph3dw1GlJRrgijIly5sqZuX7y2ZrKlNDaaYqTJldQ+fhMLmkWpDIZS6y3Wj7Zlprs2ehoErBJxiX2T395NusjQqARjQS8wWQw/3EAwj0eQHBXlQfx855MXMa0upax+xB1nMsq3wp9lErrbSCkFzxft9jubv8L/JXJIwQxeD06qJhKGIAOAU2xrsy10ipw1o8DWZOlZXN7R+M93XqrKM8lFXEeCAMW9f87Bech15A+4JUFlaLN23l7UMwcg8jt7U41Jt0dXXtqI5BJc5HIp0/9fB40VoGqxpootfJy3L7329qUVR3/Zc1YdLHPcTDt2F/XbBmO4Lf1ci9rnGvw8cUcyfw2X4pHoNDdoaZ90AGhZVGa9gVXK0TI6mNFg5u3r91XV6E=
