---
os: linux
dist: xenial
language: shell
script:
    - dpkg --list ca-certificates | cat
    - openssl s_client -servername scan.coverity.com -connect scan.coverity.com:443 -prexit -showcerts
    - openssl crl2pkcs7 -nocrl -certfile /etc/ssl/certs/ca-certificates.crt | openssl pkcs7 -print_certs -text -noout | grep -P '^\s+Subject:.*Entrust'
