os: linux
language: generic
matrix:
    include:
        -   dist: trusty
            name: trusty
        -   dist: xenial
            name: xenial
        -   dist: bionic
            name: bionic
script:
    - sysctl kernel.unprivileged_userns_clone