---
language: python
os: linux
dist: bionic

  
script:
   - pyenv versions
   - pyenv local 2.7.15 3.7.1
   - for cmd in pip pip2 pip3; do pyenv which $cmd; done
   - which python; pyenv which python